name: 365 rounds | ChoperNawers
markdown: redcarpet
highlighter: pygments
description: "365 días, 365 historias, 365 ilustraciónes."
permalink: /rounds/:title
exclude:   [node_modules,'Gruntfile.js', 'package.json']
excerpt_separator: <!--more-->
baseurl: ""

owner:
  name:           Choper
  avatar:         "choper.jpg"
  twitter:        _rodrigoibarra
  facebook:       https://www.facebook.com/killabunzz
  instagram:      http://instagram.com/killerbunnz
